### ISSUE TITLE
Error running 'bin/encore --watch"

### ISSUE THREAD

**Issue by jonscheiding** [opensalt/opensalt#602]
### Describe the problem

When I run `bin/encore dev --watch` on my Mac, webpack crashes.

### Version of OpenSALT
2.1.0

### To reproduce
Steps to reproduce the behaviour:
1. Run `bin/encore dev --watch`

### Expected behaviour
Webpack starts up and watches the files.

### Actual behaviour
Webpack builds the files, but then crashes.  Output:

```
Running webpack ...


Webpack is watching the files…

 DONE  Compiled successfully in 9246ms                                                                                                               10:20:27

 I  90 files written to web/build
module.js:557
    throw err;
    ^

Error: Cannot find module 'upath'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jonscheiding/Code/Certica/standards-connect-opensalt/node_modules/chokidar/index.js:13:13)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jonscheiding/Code/Certica/standards-connect-opensalt/node_modules/watchpack/lib/DirectoryWatcher.js:7:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at WatcherManager.getDirectoryWatcher (/Users/jonscheiding/Code/Certica/standards-connect-opensalt/node_modules/watchpack/lib/watcherManager.js:12:25)
    at WatcherManager.watchFile (/Users/jonscheiding/Code/Certica/standards-connect-opensalt/node_modules/watchpack/lib/watcherManager.js:26:14)
    at Watchpack.<anonymous> (/Users/jonscheiding/Code/Certica/standards-connect-opensalt/node_modules/watchpack/lib/watchpack.js:36:49)
    at Array.map (<anonymous>)
    at Watchpack.watch (/Users/jonscheiding/Code/Certica/standards-connect-opensalt/node_modules/watchpack/lib/watchpack.js:35:28)
    at NodeWatchFileSystem.watch (/Users/jonscheiding/Code/Certica/standards-connect-opensalt/node_modules/webpack/lib/node/NodeWatchFileSystem.js:51:16)
    at Watching.watch (/Users/jonscheiding/Code/Certica/standards-connect-opensalt/node_modules/webpack/lib/Compiler.js:116:48)
    at Watching._done (/Users/jonscheiding/Code/Certica/standards-connect-opensalt/node_modules/webpack/lib/Compiler.js:108:9)
    at compiler.emitRecords.err (/Users/jonscheiding/Code/Certica/standards-connect-opensalt/node_modules/webpack/lib/Compiler.js:79:19)
    at Compiler.emitRecords (/Users/jonscheiding/Code/Certica/standards-connect-opensalt/node_modules/webpack/lib/Compiler.js:371:38)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Your system (please complete the following information):
 - Device: desktop
 - OS: MacOS High Sierra
 - Browser: N/A
 - Version: N/A

**Comment by jonscheiding** [comment]
This is caused by having a `.yarnclean` file.  Yarn's autoclean is removing the `build` directory inside `node_modules/upath`.  PR forthcoming.

**Comment by jonscheiding** [comment]
It's possible that this varies with different versions of Yarn.  Here are my versions:

```
$ docker images node:9-alpine
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
node                9-alpine            a56170f59699        2 months ago        68.5 MB

$ docker run --rm node:9-alpine node -v
v9.11.2

$ docker run --rm node:9-alpine yarn -v
1.5.1
```
