### ISSUE TITLE
where is console-docker

### ISSUE THREAD

**Issue by chenzhikaida** [opensalt/opensalt#88]
when i exec /bin/console-docker doctrine:migrations:migrate --no-interaction ,this console-docker file is not exist

**Comment by chenzhikaida** [comment]
i use /bin/console-docker doctrine:migrations:migrate --no-interaction ,is ok

but when i access web http:myhost:3000/app_dev.php ,show You are not allowed to access this file.

i access http:myhost:3000 show follow content
`
Fatal error: Uncaught RuntimeException: Unable to create the cache directory (/var/www/html/var/cache/prod) in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:659 Stack trace: #0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(559): Symfony\Component\HttpKernel\Kernel->buildContainer() #1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(119): Symfony\Component\HttpKernel\Kernel->initializeContainer() #2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(168): Symfony\Component\HttpKernel\Kernel->boot() #3 /var/www/html/web/app.php(26): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #4 {main} thrown in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 659`

**Comment by chenzhikaida** [comment]
i solve question.
this first question ,i use consle instead console-docker file is ok
the second question is docker no vi command and php mirror no permission
